version: '3.6'

services:
  db:
    image: postgres:12.3
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    command: "postgres -c log_statement='all'"
  server:
    image: ludusrusso/confildo
    build: .
    environment:
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: db
    depends_on:
      - db
    ports:
      - 3000:3000
